# fly.toml app configuration file generated for gadgetstore on 2024-09-02T20:34:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gadgetstore'
primary_region = 'jnb'

[build]
  image = 'theuglybwe/gadgetstore:latest'

[env]
  ASPNETCORE_URLS = 'http://+:8080'
  Cloudinary__ApiKey = '877286754423351'
  Cloudinary__CloudName = 'duzqlkgil'
  StripeSettings__PublishableKey = 'pk_test_51NdrCWB0cNVyW11pdLtHofDki4FiMC9OmoPypBjiS6QdaAtcN9e3SgpFE2EHvpHBcHOotAw3bqtpTNTGYBLeWKVp00vi7rUWV1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
